#! /bin/bash

#counting how many time a word given as parameter is repeated in a file
if [ -f "$2" ]
then
	echo "Counting \"""$1"\" occurencies in "$2":""
	N=0
	while read -r LINE
	do
		for WORD in $LINE
		do
			if [ $WORD == "$1" ]
			then 
				((N++))
			fi
		done
	done < "$2"
	echo "There are "$N" repetion of \"""$1"\" in "$2"
else
	echo "no file named "$2""
	exit -1
fi	
exit 0
